### ISSUE TITLE
not working on qts5.0.0

### ISSUE THREAD

**Issue by yangchris4** [Jay-Young/qpkg#1]
nowt working on QTS 5.0.0

no pictures found in public/bingwallpapers,its empty,but text info was shown correctly.
pls fix it.

**Comment by Jay-Young** [comment]
@yangchris4 
Fixed in Version 1.2, now you can test if it saves file correctly.
[Bing Wallpaper 1.2](https://github.com/Jay-Young/qpkg#6-bing-wallpaper)

**Comment by yangchris4** [comment]
> @yangchris4 Fixed in Version 1.2, now you can test if it saves file correctly. [Bing Wallpaper 1.2](https://github.com/Jay-Young/qpkg#6-bing-wallpaper)

works fine,thx
